<?php
  class CheckListItems{
    $idt = "";
    $proc_cirur = "";
    $nome_cirur = "";
    $radio_termo = "";
    $radio_tvp = "";
    $radio_anestesica = "";
    $radio_via = "";
    $radio_anestesia = "";
    $radio_motorrizacao = "";
    $radio_viadificil = "";
    $radio_equipamento = "";
    $radio_alergia = "";
    $alergia_conhecida = "";
    $radio_risco = "";
    $radio_nausea = "";
    $radio_hipotermia = "";
    $radio_delirium = "";
    $radio_acesso = "";
    $radio_sangue = "";
    $radio_sitio = "";
    $radio_tricotomia = "";
    $hr_maltodexitrina = "";
    $horario = "";
    $radio_cirurgiao = "";
    $radio_anestesiologista = "";
    $radio_enfermeiro = "";
    $radio_confirmacao = "";
    $radio_critica = "";
    $duracao_cirur = "";
    $radio_perdasangue = "";
    $preo_espec = "";
    $radio_equipamentos = "";
    $radio_esteralizacao = "";
    $radio_bisturi = "";
    $cefazolina = "";
    $cefuroxima = "";
    $cefalotina = "";
    $outro = "";
    $outro_descri = "";
    $hr_adm = "";
    $radio_repeticao = "";
    $hr_repeticao = "";
    $hr_insisao = "";
    $radio_instrumentos = "";
    $radio_compressa = "";
    $radio_agulha = "";
    $radio_patologia = "";
    $radio_intercorrencia = "";
    $inter_cli = "";
    $nome_procedimento = "";
    $termino_cirurgia = "";
    $radio_revisao = "";
    $hr_srpa_chegada = "";
    $radio_maltodexitrina = "";
    $hr_srpa_matodexitrina = "";

    $ITEMS_POST = array("idt" => "Identificação", 
                        "proc_cirur" => "Procedimento cirúrgico",
                        "nome_cirur" => "Nome do Cirurgião",
                        "radio_termo" => "Termo de Consetimento",
                        "radio_tvp" => "Profilaxia TVP",
                        "radio_anestesica" => "Consulta Pré-Anestésica",
                        "radio_via" => "Material de via aérea",
                        "radio_anestesia" => "Aparelho de anestesia",
                        "radio_motorrizacao" => "Monotorização adequada",
                        "radio_viadificil" => "Via aérea difícil",
                        "radio_equipamento" => "Equipamento disponível",
                        "radio_alergia" => "Paciente possui alergia conhecida",
                        "alergia_conhecida" => "Campo de texto de alergia conhecida",
                        "radio_risco" => "Risco de perda sanguínea",
                        "radio_nausea" => "Risco de naúseas e vômitos",
                        "radio_hipotermia" => "Risco de hipotermia",
                        "radio_delirium" => "Risco de delirium",
                        "radio_acesso" => "Acesso endovenoso adequado",
                        "radio_sangue" => "Reserva/tipagem sanguínea",
                        "radio_sitio" => "Sítio Marcado",
                        "radio_tricotomia" => "Tricotomia",
                        "hr_maltodexitrina" => "Hora da maltodexitrina",
                        "horario" => "horario",
                        "radio_cirurgiao" => "Apresentam-se pelos nomes  -  Cirurgiões",
                        "radio_anestesiologista" => "Apresenta-se pelo nome -  Anestesiologista",
                        "radio_enfermeiro" => "Apresentam-se pelos nomes -  Equipe de Enfermagem",
                        "radio_confirmacao" => "Confimam verbalmente: identificação do paciente, sítio cirúrgico e procedimento",
                        "radio_critica" => "Etapas críticas previstas",
                        "duracao_cirur" => "Duração da cirurgia",
                        "radio_perdasangue" => "Perda sanguinea",
                        "preo_espec" => "Preocupações específicas",
                        "radio_equipamentos" => "Equipamentos",
                        "radio_esteralizacao" => "Esterelização",
                        "radio_bisturi" => "Placa de bisturi",
                        "cefazolina" => "Cefazolina",
                        "cefuroxima" => "Cefuroxima",
                        "cefalotina" => "Cefalotina",
                        "outro" => "Outro",
                        "outro_descri" => "Descrição ATB",
                        "hr_adm" => "Hora da Administração",
                        "radio_repeticao" => "Repetição da dose",
                        "hr_insisao" => "Hora da incisão cirúrgica",
                        "radio_instrumentos" => "Contagem de instrumentos correta",
                        "radio_compressa" => "Compressas",
                        "radio_agulha" => "Agulhas",
                        "radio_patologia" => "Identificação completa da amostra patológica",
                        "radio_intercorrencia" => "Intercorrências clínicas",
                        "inter_cli" => "Qual intercorrencia",
                        "nome_procedimento" => "Nome do procedimento realizado",
                        "termino_cirurgia" => "Hora do término do ato cirúrgico",
                        "radio_revisao" => "Revisão dos equipamentos",
                        "hr_srpa_chegada" => "SRPA - Hora de chegada",
                        "radio_maltodexitrina" => "SRPA - Hora da maltodexitrina",
                        "hr_srpa_matodexitrina" => "horario - maltodexitrina");


  }
?>
